### ISSUE TITLE
Minimum requirements

### ISSUE THREAD

**Issue by rcorsari** [michalsn/codeigniter-htmx#29]
Hello
just a suggestion, maybe write minimum requirements for the installation environment
e.g. PHP minimum supported version

Also, in the installation of the examples, maybe a more verbose installation guide for "dummies" that are new to Codeigniter .

Why not to allow them (I include myself to the list) to start directly with a better UX?

Thank you
Robert

**Comment by michalsn** [comment]
Thanks for the feedback. 

> just a suggestion, maybe write minimum requirements for the installation environment
e.g. PHP minimum supported version

I have added more info about the PHP version and stuff to the readme and the docs.

> Also, in the installation of the examples, maybe a more verbose installation guide for "dummies" that are new to Codeigniter .

I'm not sure what else I could put in the instructions for the demo because the installation path is quite precise, and from my point of view, nothing is missing. 

Maybe the only thing missing is information on configuring the database connection, but that is documented in the framework's user guide. I see no point in redundancy.

Do you have any suggestions on what is missing?

**Comment by rcorsari** [comment]
Sure it is comprehensive for experienced Coders with lot of familiarity with Codeigniter :-) and related procedures.

Together with the installation, could it be an idea to provide a full Codeigniter tree zipped with already HTMX operational with examples?

Anyway thank you

**Comment by michalsn** [comment]
Okay, now I understand.

Unfortunately, I like the idea of this project and a demo being distributed as a separate package that you can easily add to your existing project.

A complete CodeIgniter installation + this library + demo as a ZIP archive will not happen. Sorry.
